services:
  - type: web
    name: ollama-remote-engine
    env: docker
    plan: free # Change to 'starter' if you want it to be faster
    region: oregon # Or your closest region
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
      - key: OLLAMA_ORIGINS
        value: "*"
    dockerCommand: ollama serve
